env:
    credentials: "ENCRYPTED[!666a103cc67ef0bdce1a046ee4f382a3cce0b5867cc1b38b24b52236d45f82ecbd63181e02334d46bc15e9d4f2836b6c!]"
    rcloneconfig: "ENCRYPTED[!9dd3f79ceb94286194668415bd8504a3d2e2aaf6569d9bc8226838dfa4f7ca516ad7b3e6f290b2d74ec6b2d577983f43!]"
    tokentl: "ENCRYPTED[!d167e56e40cf1f643ec7aaa9e5acfa30877d409da15d199596a2e164ef64361db7b07dae620389b91414d354052a5d12!]"
    idtl: "ENCRYPTED[!d266d83de82272fa43816c32ec86495d2f91a444c1d86b1cf4f58d44e7fd7bb9643ca23eb4f086596883202f76c1fcbf!]"
    lunch: lunch nad_RMX2020-user
    make: make nad

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "MeAbidin"
       - git config --global user.email "dintzonly17@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy RMX2020:nusantara/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest -b 10-mtk
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/nad.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/nusantara/config/branding.mk
      - git clone --depth=1 https://github.com/MeAbidin/device_realme_RMX2020 -b Nusantara device/realme/RMX2020
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="Meabidin"
      - export BUILD_HOSTNAME="Woodyy17"
      - export KBUILD_BUILD_USER="MeAbidin"
      - export KBUILD_BUILD_HOST="Woodyy17"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Nusantara for RMX2020 Started!"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/RMX2020/ && ls Nusantara*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz RMX2020:nusantara -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

